"""
Constantes para eventos de logging del servidor.
Centraliza la sintaxis de eventos para mantener consistencia.
"""

# Eventos del servidor
SERVER_START = "SERVER_START"
PLAYER_CONNECTED = "PLAYER_CONNECTED"
QUEUE_ADD = "QUEUE_ADD"
PLAYER_DISCONNECTED = "PLAYER_DISCONNECTED"
PLAYER_EXIT = "PLAYER_EXIT"
PLAYER_CONNECTION_LOST = "PLAYER_CONNECTION_LOST"
MATCH_CREATED = "MATCH_CREATED"

# Eventos de sesión
SESION_CREADA = "MATCH_SESSION_CREATED"
SESION_INICIADA = "MATCH_START"
SESION_TERMINADA = "MATCH_TERMINATED"

# Eventos de colocación de barcos
BARCO_COLOCADO = "BOAT_PLACED"
ERROR_COLOCACION = "BOAT_PLACEMENT_ERROR"

# Eventos de turnos y disparos
PRIMER_TURNO = "MATCH_FIRST_TURN"
CAMBIO_TURNO = "TURN_CHANGE"
DISPARO = "SHOT"
ERROR_DISPARO = "SHOT_ERROR"

# Eventos de fin de partida
GANADOR = "MATCH_WINNER"
JUGADOR_DESCONECTADO = "MATCH_PLAYER_DISCONNECTED"
