# config/log_events.py

"""
Constants for server logging events.
Centralizes event syntax for consistency.
"""

# Server events
SERVER_START = "SERVER_START"
PLAYER_CONNECTED = "PLAYER_CONNECTED"
QUEUE_ADD = "QUEUE_ADD"
PLAYER_DISCONNECTED = "PLAYER_DISCONNECTED"
PLAYER_EXIT = "PLAYER_EXIT"
PLAYER_CONNECTION_LOST = "PLAYER_CONNECTION_LOST"
MATCH_CREATED = "MATCH_CREATED"

# Session events
SESSION_CREATED = "MATCH_SESSION_CREATED"
SESSION_STARTED = "MATCH_START"
SESSION_ENDED = "MATCH_TERMINATED"

# Ship placement events
SHIP_PLACED = "BOAT_PLACED"
PLACEMENT_ERROR = "BOAT_PLACEMENT_ERROR"

# Turn and shot events
FIRST_TURN = "MATCH_FIRST_TURN"
TURN_CHANGE = "TURN_CHANGE"
SHOT = "SHOT"
SHOT_ERROR = "SHOT_ERROR"

# Game end events
WINNER = "MATCH_WINNER"
PLAYER_DISCONNECTED = "MATCH_PLAYER_DISCONNECTED"